const path = require("path");

// Using a Set to automatically handle duplicate URLs
const URLS_TO_SCRAPE = [
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1075",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1086",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1087",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1096",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1277",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1278",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1282",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1287",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1360",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1372",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1376",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1393",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1412",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1465",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1466",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1483",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1485",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1512",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1521",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1576",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1688",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1727",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1732",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1751",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1865",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB1940",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2082",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2158",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2207",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2257",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2259",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2286",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2287",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2289",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2374",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2516",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2518",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2728",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2743",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2758",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2770",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2771",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2772",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2777",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2779",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2788",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2789",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2790",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2793",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=HB2903",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB102",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB1024",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB105",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB1126",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB1129",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB1137",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB1140",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB1141",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB1143",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB1150",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB1151",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB1152",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB1153",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB1155",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB1169",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB1180",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB135",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB190",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB251",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB31",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB335",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB341",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB391",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB393",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB394",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB395",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB396",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB434",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB443",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB460",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB469",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB480",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB527",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB553",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB56",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB672",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB676",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB711",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB745",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB752",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB794",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB796",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB806",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB813",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB814",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB840",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB841",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB912",
  "https://www.oklegislature.gov/BillInfo.aspx?Bill=SB940",
];

const DOWNLOAD_DIR = path.join(__dirname, "downloads");
const RETRY_COUNT = 4;
const RETRY_DELAY_MS = 2000; // 2 seconds
const BATCH_SIZE = 5; // Process 5 URLs at a time

module.exports = {
  URLS_TO_SCRAPE: [...new Set(URLS_TO_SCRAPE)], // Remove duplicates
  DOWNLOAD_DIR,
  RETRY_COUNT,
  RETRY_DELAY_MS,
  BATCH_SIZE,
};
